// Authentication
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const POST_REGISTER_REQUEST = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILURE = 'POST_REGISTER_FAILURE';

export const POST_VERIFY_OTP_REQUEST = 'POST_VERIFY_OTP_REQUEST';
export const POST_VERIFY_OTP_SUCCESS = 'POST_VERIFY_OTP_SUCCESS';
export const POST_VERIFY_OTP_FAILURE = 'POST_VERIFY_OTP_FAILURE';

// Utils
export const GET_BANER_REQUEST = 'GET_BANER_REQUEST';
export const GET_BANER_SUCCESS = 'GET_BANER_SUCCESS';
export const GET_BANER_FAILURE = 'GET_BANER_FAILURE';