// Authentication
export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

// Utils
export const GET_BANER_REQUEST = 'GET_BANER_REQUEST';
export const GET_BANER_SUCCESS = 'GET_BANER_SUCCESS';
export const GET_BANER_FAILURE = 'GET_BANER_FAILURE';